import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's GitHub repository
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((m) => `node:${m}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  // 資格情報を `define` で注入しないのは意図的。ビルド時に何も差し込まないので、
  // 配布された main.js はコミット済みソースの純粋な関数であり、社員の誰でもタグを
  // チェックアウトして `npm ci && npm run build` すればバイト単位で再現できる。
  // OAuth クライアントは利用者が実行時に設定画面へ入力する（ADR は docs/adr/ を参照）。
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
